name: CI/CD Tienda Perritos - DB
on:
  push:
    branches: [ "deploy" ]
    paths:
      - "db/**"
  workflow_dispatch:

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push a ECR
        run: |
          cd db
          docker build -t tienda-db .
          docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB }}:latest
          docker push ${{ secrets.ECR_REPO_URL_DB }}:latest

      - name: Desplegar DB via Frontend → Backend → DB
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO_URL_DB: ${{ secrets.ECR_REPO_URL_DB }}
          EC2_BACKEND_HOST: ${{ secrets.EC2_BACKEND_HOST }}
          EC2_DB_HOST: ${{ secrets.EC2_DB_HOST }}
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: AWS_REGION,ECR_REGISTRY,ECR_REPO_URL_DB,EC2_BACKEND_HOST,EC2_DB_HOST
          script: |
            # Pull imagen DB en el frontend (tiene internet)
            aws ecr get-login-password --region $AWS_REGION | \
              docker login --username AWS --password-stdin $ECR_REGISTRY
            docker pull $ECR_REPO_URL_DB:latest

            # Enviar imagen al backend, y desde el backend a la DB
            docker save $ECR_REPO_URL_DB:latest | \
              ssh -i ~/.ssh/Devops.pem \
                  -o StrictHostKeyChecking=no \
                  ec2-user@$EC2_BACKEND_HOST \
                  "docker load && \
                   docker save $ECR_REPO_URL_DB:latest | \
                   ssh -i ~/.ssh/Devops.pem \
                       -o StrictHostKeyChecking=no \
                       ec2-user@$EC2_DB_HOST \
                       'docker load; \
                        docker stop tienda-db || true; \
                        docker rm tienda-db || true; \
                        docker run -d --name tienda-db --restart always \
                        -p 3306:3306 \
                        -v dbdata:/var/lib/mysql \
                        $ECR_REPO_URL_DB:latest'"
